import type { Metadata } from "next";
import "./globals.css";
import connect from "@/db/db";
import Navbar from "@/components/navbar";
import Providers from "./providers";

connect();

export const metadata: Metadata = {
  title: "KUDO",
  description: "Generated by Vibe Coder :)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-950">
        <Navbar />
        <Providers>
          <main className="mt-20 ">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
